---
namespace: "tcharl"
name: "ansible_users"
version: "1.0.1"
description: "Ansible roles that manages freeipa users"

authors:
  - "Charlie Mordant <cmordant1@gmail.com>"

repository: "https://github.com/OsgiliathEnterprise/ansible-users"
documentation: "https://github.com/OsgiliathEnterprise/ansible-users/blob/master/README.md"
homepage: "https://github.com/OsgiliathEnterprise/ansible-users"
issues: "https://github.com/OsgiliathEnterprise/ansible-users/issues"

readme: "README.md"
license:
  - "Apache-2.0"
tags:
  - "linux"
  - "freeipa"
  - "users"
