---
roles:
  # Install a role from Ansible Galaxy.
  - name: robertdebock.users

  - name: robertdebock.bootstrap

  - name: robertdebock.core_dependencies

  - name: tcharl.ansible_routing

  - name: tcharl.ansible_securehost

  - name: tcharl.ansible_hostname

  - name: robertdebock.fail2ban

  - name: robertdebock.epel

  - name: geerlingguy.ntp
