---
- name: ansible-users | deps | import core_dependencies role
  ansible.builtin.include_role:
    name: robertdebock.core_dependencies
  vars:
    ansible_become: true

- name: ansible-users | deps | import bootstrap role
  ansible.builtin.include_role:
    name: robertdebock.bootstrap
  vars:
    ansible_become: true
