---
# tasks file for ansible-users

- name: Requirements
  ansible.builtin.import_tasks: requirements.yml
  when: standalone_role

- name: Reboot ipa
  ansible.builtin.service:
    name: ipa
    state: restarted
  failed_when: false
  changed_when: false
  become: true

- name: Loop over ipa_users_group_list
  ansible.builtin.include_tasks: ipa-groups.yml
  loop: "{{ ipa_users_group_list }}"
  loop_control:
    label: "{{ group.name }}"
    loop_var: group
  when:
    - idm_group | default("") | string in group_names
    - ipa_users_group_list is defined

- name: Loop over ipa_users_user_list
  ansible.builtin.include_tasks: ipa-users.yml
  loop: "{{ ipa_users_user_list }}"
  loop_control:
    label: "{{ user.name }}"
    loop_var: user
  when:
    - idm_group | default("") | string in group_names
    - ipa_users_user_list is defined
