---
# This is a basic workflow to help you get started with Actions
name: Molecule

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:
    branches:
      - master
      - tags/*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: install lint prerequisite
      run: |
        sudo apt update
        sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt -y install python3-setuptools ansible-lint python3 python3-pip docker-ce

    - name: Install molecule
      run: |
        sudo pip3 install wheel docker
        sudo pip3 install molecule molecule-docker testinfra yamllint ansible-lint flake8

    - name: molecule lint
      run: |
        molecule lint

  requirements:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: install requirements prerequisite
      run: |
        sudo apt update
        sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt -y install python3-setuptools ansible-lint python3 python3-pip docker-ce

    - name: Install molecule
      run: |
        sudo pip3 install wheel docker
        sudo pip3 install molecule molecule-docker testinfra yamllint ansible-lint flake8
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: install prereq
      run: |
        ./configure

  molecule:
    runs-on: ubuntu-latest
      # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: install tests prerequisite
      run: |
        sudo apt update
        sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt -y install python3-setuptools ansible-lint python3 python3-pip docker-ce

    - name: Install molecule
      run: |
        sudo pip3 install wheel docker
        sudo pip3 install molecule molecule-docker testinfra yamllint ansible-lint flake8

    - name: execute molecule
      run: |
        sudo molecule test
