---
# This is a basic workflow to help you get started with Actions
name: Molecule

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:
    branches:
      - master
      - tags/*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: add vagrant apt key
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      - name: add vagrant apt repository
        run: |
          echo \
            "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      - name: update apt
        run: |
          sudo apt update
#      - name: apt upgrade
#        run: |
#          sudo apt upgrade
      - name: install molecule apt prerequisite
        run: |
          sudo apt -y install bridge-utils dnsmasq-base ebtables ca-certificates curl gcc iproute2 sudo rustc python3 python3-pip python3-setuptools docker-ce docker-ce-cli containerd.io
      - name: pip install packages
        run: |
          pip3 install wheel setuptools-rust netaddr
          pip3 install pyopenssl yamllint pytest-testinfra flake8 ansible ansible-lint molecule molecule-docker jmespath
          pip3 install -U PyYAML
#      - name: Test KVM conditions fails
#        run: |
#          sudo kvm-ok
      - name: molecule lint
        run: |
          molecule lint

  requirements:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: install prereq
        run: |
          ansible-galaxy role install -r requirements.yml

  molecule:
    runs-on: ubuntu-latest
      # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: add docker apt key
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      - name: add docker apt repository
        run: |
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      - name: update apt
        run: |
          sudo apt update
#      - name: apt upgrade
#        run: |
#          sudo apt upgrade

      - name: install tests prerequisite
        run: |
          sudo apt -y install bridge-utils dnsmasq-base ebtables ca-certificates curl gcc iproute2 sudo rustc python3 python3-pip python3-setuptools docker-ce docker-ce-cli containerd.io
      - name: Install molecule
        run: |
          pip3 install wheel setuptools-rust netaddr testresources
#         pip3 install ansible==2.9.22
          pip3 install pyopenssl netaddr ansible yamllint pytest-testinfra flake8 ansible-lint molecule molecule-docker jmespath
          pip3 install -U PyYAML
      - name: execute molecule
        run: |
          molecule test
